const SAVEACTIVITY = 'SAVEACTIVITY';
const NEWTEMPACTIVITY = 'NEWTEMPACTIVITY';
const SAVENEWACTIVITY = 'SAVENEWACTIVITY';
const UPDATEACTIVITIES = 'UPDATEACTIVITIES';

export {
    SAVEACTIVITY,
    NEWTEMPACTIVITY,
    SAVENEWACTIVITY, 
    UPDATEACTIVITIES
};
