const SAVEACTIVITY = 'SAVEACTIVITY';
const NEWTEMPACTIVITY = 'NEWTEMPACTIVITY';
const SAVENEWACTIVITY = 'SAVENEWACTIVITY';
const UPDATEACTIVITIES = 'UPDATEACTIVITIES';
const SELECTACTIVITY = 'SELECTACTIVITY';
const DISCARDCURRENTACTIVITY ='DISCARDCURRENTACTIVITY';

export {
    SAVEACTIVITY,
    NEWTEMPACTIVITY,
    SAVENEWACTIVITY, 
    UPDATEACTIVITIES,
    SELECTACTIVITY,
    DISCARDCURRENTACTIVITY
};
